version: "1"

services:
  product-server:
    build: ./server
    image: aeolusjzane/dockercompose:server

  product-web:
    image: nginx:alpine
    volumes:
      - ./front/dist:/usr/share/nginx/html
    depends_on:
      - product-server

  nginx-gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - product-server
      - product-web
